#!/usr/bin/env bash
# File: scripts/check-service-access.sh
# Purpose: Preflight that required service credentials are reachable; (re)generate .service-access.local.json.
#          Extend the per-service checks as you add services to docs/service-access.md.
# See: docs/workspace-structure.md → "Service Access Pattern"
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

echo "Service access preflight"
status="ok"

# --- GitHub (gh CLI + MCP token) ---
if command -v gh >/dev/null 2>&1; then
  if gh auth status >/dev/null 2>&1; then echo "  ✓ gh authenticated"
  else echo "  ✗ gh not authenticated — run: gh auth login" >&2; status="degraded"; fi
else
  echo "  ! gh CLI not found (optional, but needed for the GitHub token source)"; status="degraded"
fi

if [ -n "${GITHUB_PERSONAL_ACCESS_TOKEN:-}" ]; then
  echo "  ✓ GITHUB_PERSONAL_ACCESS_TOKEN exported (length ${#GITHUB_PERSONAL_ACCESS_TOKEN})"
else
  echo "  ! GITHUB_PERSONAL_ACCESS_TOKEN not set — export: GITHUB_PERSONAL_ACCESS_TOKEN=\$(gh auth token)"
fi

# --- cache (gitignored) so agents don't re-discover the commands ---
cat > .service-access.local.json <<'JSON'
{
  "_comment": "Generated by scripts/check-service-access.sh — gitignored. Resolved retrieve/verify commands per service.",
  "github": {
    "tokenSource": "gh auth token",
    "export": "GITHUB_PERSONAL_ACCESS_TOKEN=$(gh auth token)",
    "verify": "gh auth status"
  }
}
JSON
echo "  wrote .service-access.local.json"
echo "Status: $status"
