#!/usr/bin/env bash
# File: scripts/check-drift.sh
# Purpose: Read-only staleness sweep. One line per finding; exit 1 if any
#          `DRIFT` line, 0 if clean or only `WARN` lines. Checks:
#            1. dead backticked docs/…, skills/…, scripts/… paths in tracked .md
#               files (work/, docs/archive/, docs/superpowers/ skipped; ADRs are
#               history, so their hits are WARN)
#            2. operational-knowledge gotchas past the 6-month review age
#            3. CONTEXT.md over its Z0 byte budget
#            4. docs/ entries not linked from docs/README.md
#          DRIFT_ROOT overrides the workspace root (tests).
# See: docs/workspace-structure.md → "scripts/ — Bootstrap and Utility Scripts"
# run-checks: slow
# (fast, but a gotcha ages past review with no commit, and only a person can
#  re-confirm it — so it stays out of pre-commit; CI runs it, weekly too.)
set -uo pipefail

ROOT="${DRIFT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$ROOT" || exit 2

# CONTEXT.md budget: ~4K tokens at ~4 bytes/token, the target the L51 trim set
# inside the Z0 band (docs/zoom-model.md). Over it, repair in this order: move
# content to its proper home (a doc CONTEXT.md links to), then condense; raise
# this number only with the reason stated in the commit.
CONTEXT_MAX_BYTES=16000

# Paths that look dead but aren't — one per line, `path  # reason`. Prefix match.
ALLOW='
skills/engineering/         # upstream provenance lines in vendored skills
skills/in-progress/         # upstream provenance lines in vendored skills
skills/typesafe-ai/         # upstream provenance lines in vendored skills
docs/agents/domain.md       # generated by setup-matt-pocock-skills
docs/agents/triage-labels.md  # generated by setup-matt-pocock-skills
scripts/rlm_repl.py         # relative to skills/rlm/
scripts/hitl-loop.template.sh # relative to its skill folder
scripts/rollover-prep.sh    # removed; operational-knowledge names it as history
'
allowed() {
  local p="$1" a
  while read -r a _; do
    [ -n "$a" ] && case "$p" in "$a"*) return 0 ;; esac
  done <<< "$ALLOW"
  return 1
}

fail=0
drift() { echo "DRIFT $*"; fail=1; }
warn()  { echo "WARN $*"; }

# 1. Dead path references (the loop runs in a subshell, so read fail back from its output).
paths=$(git ls-files '*.md' | grep -v -E '^(work/|docs/archive/|docs/superpowers/)' |
while read -r f; do
  grep -o -E '`(docs|skills|scripts)/[^`]*`' "$f" | tr -d '`' | awk '{print $1}' |
    sed -E 's/[:#].*$//; s/[.,;)]+$//' | grep -v -E '[*<>{}]|…|\.\.\.|NN' | sort -u |
  while read -r p; do
    [ -e "$p" ] || allowed "$p" && continue
    if [ "${f#docs/adr/}" != "$f" ]; then warn "$f: $p (ADR history)"; else drift "$f: $p"; fi
  done
done)
[ -n "$paths" ] && echo "$paths"
grep -q '^DRIFT ' <<< "$paths" && fail=1

# 2. Gotchas past review age (checkpoint step 1 runs this script for it).
if [ -f docs/operational-knowledge.md ]; then
  cutoff=$(date -v-6m +%F 2>/dev/null || date -d '6 months ago' +%F)
  while read -r line; do
    [ -n "$line" ] && drift "gotcha past review age: $line"
  done < <(awk -v c="$cutoff" '/^## /{h=$0} /^\*\*Last confirmed:\*\*/{if ($3 < c) print $3, h}' docs/operational-knowledge.md)
fi

# 3. CONTEXT.md byte budget.
if [ -f CONTEXT.md ]; then
  bytes=$(wc -c < CONTEXT.md | tr -d ' ')
  [ "$bytes" -gt "$CONTEXT_MAX_BYTES" ] &&
    drift "CONTEXT.md is $bytes bytes, over its $CONTEXT_MAX_BYTES-byte Z0 budget — move content to its proper home first, then condense; raise the limit only with a stated reason"
fi

# 4. docs/ entries missing from the index.
if [ -f docs/README.md ]; then
  while read -r n; do
    case "$n" in README.md|.*) continue ;; esac   # the index itself; dotfiles like .nojekyll
    grep -q -E "\]\($n([/)#]|\))" docs/README.md || drift "docs/$n not linked from docs/README.md"
  done < <(git ls-files docs | cut -d/ -f2 | sort -u)
fi

exit "$fail"
