#!/usr/bin/env bash
# File: scripts/check-service-access.sh
# Purpose: Preflight that required service credentials are reachable; (re)generate
#          .service-access.local.json. Verify + INSTRUCT only — it never logs you in
#          or stores secrets. When something's missing it prints exact fix commands;
#          an AI agent or human then follows docs/runbooks/authentication.md.
#          Required services missing → exit 1 (same hard-fail distinction as
#          check-dependencies.sh). Optional services missing → warn only, exit 0.
# See: docs/workspace-structure.md → "Service Access Pattern"
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

case "$(uname -s)" in
  Darwin) OS=macOS ;; Linux) OS=Linux ;; MINGW*|MSYS*|CYGWIN*) OS=Windows ;; *) OS=unknown ;;
esac
echo "Service access preflight (OS: $OS)"
status="ok"
missing_required=0

# Required services hard-fail (missing_required=1 → exit 1); optional services
# would only set status="degraded". Today GitHub is the sole — and required —
# service; add optional ones below the required block as the registry grows.

# --- GitHub (required): gh CLI present + authenticated ---
if command -v gh >/dev/null 2>&1; then
  if gh auth status >/dev/null 2>&1; then
    echo "  ✓ gh authenticated"
  else
    echo "  ✗ gh not authenticated" >&2
    echo "    fix: gh auth login" >&2
    status="degraded"; missing_required=1
  fi
else
  echo "  ✗ gh CLI not found" >&2
  case "$OS" in
    macOS)   echo "    fix: brew install gh && gh auth login" >&2 ;;
    Linux)   echo "    fix: see https://github.com/cli/cli#installation, then gh auth login" >&2 ;;
    Windows) echo "    fix: winget install GitHub.cli  (then gh auth login)" >&2 ;;
    *)       echo "    fix: install gh, then gh auth login" >&2 ;;
  esac
  status="degraded"; missing_required=1
fi

# --- cache (gitignored) so agents don't re-discover the commands ---
cat > .service-access.local.json <<'JSON'
{
  "_comment": "Generated by scripts/check-service-access.sh — gitignored. Resolved retrieve/verify commands per service.",
  "github": {
    "tokenSource": "gh keychain (managed by gh auth login)",
    "verify": "gh auth status"
  }
}
JSON
echo "  wrote .service-access.local.json"

echo "Status: $status"
[ "$status" = "ok" ] || echo "Some services need setup — follow docs/runbooks/authentication.md" >&2
[ "$missing_required" = 0 ] || exit 1
exit 0
